################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: friday
      time: "22:00"
      timezone: Asia/Bangkok
    cooldown:
      default-days: 7
    assignees:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - dependencies
