# Version: 0.1.6

StylesPath = styles
MinAlertLevel = suggestion
Vocab = DNB, Tech, Thailand

Packages = Microsoft, Google, Hugo, alex, proselint, Readability, write-good

# Ignoring scopes
IgnoredScopes = code, tt
SkippedScopes = script, style, pre, blockquote
IgnoredClasses = highlight

[formats]
mdx = md

[*.{md,txt}]
BasedOnStyles = Vale, Microsoft, Google, alex, proselint, Readability, write-good, DNB

# rules from Vale
Vale.Spelling = warning
# rules from Microsoft
Microsoft.Avoid = NO
Microsoft.FirstPerson = NO
Microsoft.We = NO
Microsoft.Contractions = NO
Microsoft.Passive = NO
Microsoft.Quotes = NO
Microsoft.RangeFormat = NO
Microsoft.Vocab = NO
# rules from Google
Google.Contractions = NO
Google.FirstPerson = NO
Google.Parens = NO
Google.Passive = NO
Google.We = NO
Google.Quotes = NO
Google.Exclamation = NO
Google.Ordinal = NO
Google.OptionalPlurals = NO
Google.Units = NO
# rules from alex
alex.ProfanityUnlikely = NO
alex.Condescending = NO
# rules from proselint
proselint.Cliches = NO
proselint.Very = NO
proselint.Skunked = NO
# rules from write-good
write-good.E-Prime = NO
write-good.Passive = NO
write-good.ThereIs = NO
write-good.So = NO
write-good.Weasel = Warning
# rules from DNB
DNB.OpenlyA11Y = warning
DNB.OpenlyAnthropomorphism = warning
DNB.OpenlyBut = warning
DNB.OpenlyClarity = warning
DNB.OpenlyEPrime = warning
DNB.OpenlyFutureTense = warning
DNB.OpenlyGenderBias = warning
DNB.OpenlyHeadingsPunctuation = warning
DNB.OpenlyHedging = warning
DNB.OpenlyHyphens = warning
DNB.OpenlyLink = warning
DNB.OpenlyQuoteType = warning
DNB.OpenlyReadability = warning
DNB.OpenlySentenceLength = warning
DNB.OpenlySo = warning
DNB.OpenlyThereIs = warning
DNB.OpenlyTitles = warning
DNB.OpenlyUnclearAntecedent = warning
DNB.OpenlyVerbingNouns = warning
